version: '2.0'
orbs:
  node: circleci/node@5.0.2
jobs:
  
  npm_build: &npm_build
    docker:
      - image: circleci/node:latest
    working_directory: ~/node-server-employee-data
    steps:
      - checkout
      - run: bash ./terraform_project/scripts/npm_build.sh

  npm_unit_test: &npm_unit_test
    docker:
      - image: circleci/node:latest # use the default executor defined within the orb
    steps:
      - checkout
      - run: bash ./scripts/npm-test.sh

  deploy: &deploy-env
    docker:
      - image: circleci/node:latest
    
    working_directory: ~/node-server-employee-data/terraform_project

    steps:
      - checkout 
      - setup_remote_docker
      - run : 
          name: deploy-script
          command: |
            echo "deploy"
            echo $(pwd)
            echo ${tag}
            echo $PATH
            echo $TARGET_ENV_DEV
            bash ./terraform_project/scripts/terraform_install.sh   
            ls -al
            bash ./terraform_project/scripts/before_script_deploy.sh
            bash ./terraform_project/scripts/deploy_script.sh
            echo `deployed successfully in $DEPLOY_ENVIRONMENT environment`
  
  # .debug_logic: &debug_logic
  #   - run : 
  #       command: |
  #         if ["$DEBUG=true"] ; then
  #           set -xv
  #           echo "ARTIFACT_ID is $ARTIFACT_ID"
  #           echo "VERSION is $APP_VERSION"
  #           echo "NEXT_DEVELOPEMENT_VERSION is $NEXT_DEVELOPEMENT_VERSION"
  #           echo "prinitng package.json file"
  #           cat package.json
  #           git config --list
  #         fi
  
  # .only_branch_default: &only_branch_default
  #   only:
  #     - /^feature/.*$/
  #     - /^hotfix/.*$/
  #     - /^bugfix/.*$/
  #     - merge_requests
  #   except:
  #     refs:
  #       - main
  #       - tags
  
  # .except_master: &except_master
  #   rules:
  #     - if: $CIRCLE_BRANCH=="master"
  #       when: never
  #     - when: on_success
  
  # .only_merge_request: &only_merge_request
    

  init-before-script: &init-before-script
    docker:
        - image: cimg/python:3.10.6
    working_directory: ~/
    steps:
      - run : 
          name: beofre_script
          command: |
            echo $(pwd)
            mkdir .aws
            mkdir .jfrog
            mkdir .m2
            ls -al
            pip install --upgrade pip
            pip install semver # https://python-semver.readthedocs.io/en/2.9.0/index.html
            if [ "$DEBUG" = true ] ; then
              ls -alrt ~/.aws && ls -alrt ~ && ls -alrtr ~/.jfrog/ && ls -alrt ~/.m2
            fi

  init-before:
    <<: *init-before-script
    environment:
      DEBUG: true
# https://circleci.com/docs/workspaces
  init:
    docker:
      - image: cimg/python:3.10.6
    working_directory: ~/node-server-employee-data
    steps:
      - checkout 
      - setup_remote_docker
      - run: bash ./scripts/init-script.sh
          # Persist the specified paths (workspace/build.env) into the workspace for use in build job.
      - persist_to_workspace:
          # Must be an absolute path, or relative path from working_directory. This is a directory on the container which is
          # taken to be the root directory of the workspace.
          root: .
          # Must be relative path from root
          paths:
            - build.env
    environment:
      DEBUG: true
      VARIABLE_FILE: build.env
            
  build:
    docker:
      - image: circleci/node:latest
    working_directory: ~/node-server-employee-data
    steps:
      - checkout
      - persist_to_workspace:
          root: target
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: .
      - run: bash ./scripts/npm_build.sh
    environment:
      tag: dev
      ARTIFACTORY_URL: "https://devopsamiya.jfrog.io/artifactory/snapshots-npm/"
      PROJECT_NAME: node-server-employee-data
      VARIABLE_FILE: build.env  

  test:
    <<: *npm_unit_test
    environment:
      tag: dev
      POSTGRESS_USER: "postgres"
      POSTGRESS_DB: "employee_data"
      PGPASSWORD: "mypassword"

  deploy_dev:
    <<: *deploy-env
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: ./target
    environment:
      DEPLOY_ENVIRONMENT: dev

  deploy_qa:
    <<: *deploy-env
    environment:
      DEPLOY_ENVIRONMENT: qa
    
  deploy_uat:
    <<: *deploy-env
    environment:
      DEPLOY_ENVIRONMENT: uat

  deploy_prod:
    <<: *deploy-env
    environment:
      DEPLOY_ENVIRONMENT: prod

workflows:
  version: 2
  # this aws-cli workflow for terraform work
  stage_workflow:
    jobs:
      - init-before:
          filters:
            branches:
              only: /^feature/.*$/
      - init:
          filters:
            branches:
              only: /^feature/.*$/
          requires:
            - init-before
      - build:
          filters:
            branches:
              only: /^feature/.*$/
          requires:
            - init
      - test:
          filters:
            branches:
              only: /^feature/.*$/
          requires:
            - build
      - deploy_dev:
          filters:
            branches:
              only: /^feature/.*$/
          requires:
            - build
      - trigger_qa:
          type: approval
      - deploy_qa:
          filters:
            branches:
              only: main
          requires:
            - trigger_qa
            - deploy_dev
      - trigger_uat:
          type: approval
      - deploy_uat:
          filters:
            branches:
              only: main
          requires:
            - trigger_uat
            - deploy_qa
      - trigger_prod:
          type: approval
      - deploy_prod:
          filters:
            branches:
              only: main
          requires:
            - trigger_prod
            - deploy_uat