version: 2
orbs:
  # node: circleci/node@5.0.2
  aws-cli: circleci/aws-cli@2.0
jobs:
  aws-cli-cred-setup:
    executor: aws-cli/default
    steps:
      - aws-cli/setup:
          aws-access-key-id: AWS_ACCESS_KEY
          aws-secret-access-key: AWS_SECRET_KEY
  
  build:
    docker:
      - image: circleci/node:latest
    working_directory: ~/node-server-employee-data
    # environment:
    #   TARGET_ENV_DEV        : dev
    #   TARGET_ENV_QA         : qa
    #   TARGET_ENV_UAT        : uat
    #   TARGET_ENV_PROD       : prod
    #   TARGET_AWS_REGION : my-value-2
    
    steps:
     - checkout
     - setup_remote_docker
     - run: echo "build docker image with required instllation of node and git"
     - run: echo "Node versiopn in docker is"
     - run: node --version
     - run: npm install --save-dev
    
  npm_build_and_test: &npm_build_and_test # this can be any name you choose
    docker:
      - image: circleci/node:latest # use the default executor defined within the orb
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn test
          name: Run tests
      - run:
          command: yarn build
          name: Build app
      - persist_to_workspace:
          root: ~/node-server-employee-data
          paths:
            - .

  deploy: &deploy-env
    docker:
      - image: circleci/node:latest
    
    working_directory: ~/node-server-employee-data/terraform_project

    steps:
      - checkout 
      - setup_remote_docker

      # - run: echo "deploy"
      # - run: bash ./scripts/install_terraform.sh
      # - run: bash ./scripts/apply_${tag}.sh
      # - run: echo "deployed successfully"

      - run: echo "deploy"
      - run: echo $(pwd)
      - run: echo ${tag}
      - run: echo $PATH
      - run: echo $TARGET_ENV_DEV
      # - run: sudo chmod 777 install_terraform.sh
      # - run: bash install_terraform.sh
      - run : 
          name: terraform installation
          command: |
            sudo apt-get install wget unzip -y
            sudo apt-get install file
            wget https://releases.hashicorp.com/terraform/1.2.2/terraform_1.2.2_linux_amd64.zip
            unzip terraform_1.2.2_linux_amd64.zip
            ls -a
            chmod +x terraform
            file terraform
            uname -a
            sudo mv terraform /usr/local/bin
            terraform -v
      - run: ls -al
      - run: bash ./terraform_project/scripts/apply_${tag}.sh
      # - run: bash terraform -v
      # - run: bash terraform init
      # - run: bash ./scripts/terraform_plan.sh
      # - run: bash ./scripts/terraform_apply.sh
      - run: echo `deployed successfully in ${tag} environment`

  deploy_dev:
    <<: *deploy-env
    environment:
      tag: dev

  deploy_qa:
    <<: *deploy-env
    environment:
      tag: qa
  
  deploy_uat:
    <<: *deploy-env
    environment:
      tag: uat

  deploy_prod:
    <<: *deploy-env
    environment:
      tag: prod
  
  npm_build_test:
    <<: *npm_build_and_test
    environment:
      tag: dev

workflows:
  version: 2
  stage_workflow:
    jobs:
      - aws-cli-cred-setup:
          filters:
            branches:
              only: main
      #       # context: aws
      - build:
          filters:
            branches:
              only: main
      - npm_build_test:
          filters:
            branches:
              only: main
          requires:
            - build
      - deploy_dev:
          filters:
            branches:
              only: main
          requires:
            - build 
      - deploy_qa:
          filters:
            branches:
              only: main
          requires:
            - build 
      - deploy_uat:
          filters:
            branches:
              only: main
          requires:
            - build 
      - deploy_prod:
          filters:
            branches:
              only: main
          requires:
            - build 
            